name: style

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # The final 1 indicates that we want to run this test on Tuesdays, making
    # this a weekly test.
    - cron:  '30 2 * * 1'
  pull_request:
  push:
    branches: main

env:
  CARGO_TERM_COLOR: always

jobs:
  style:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: rustfmt
      run: |
        rustup toolchain install nightly
        rustup default nightly
        rustup component add rustfmt

    - name: style
      run: rustfmt --check --edition 2021 mapf/src/lib.rs mapf-viz/src/lib.rs
