name: style

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  style:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: rustfmt
      run: |
        rustup toolchain install nightly
        rustup default nightly
        rustup component add rustfmt

    - name: style
      run: rustfmt --check --edition 2021 mapf/src/lib.rs mapf-viz/src/lib.rs
